apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.namespace | default "nginx-web" }}
  labels:
    app: nginx-web
spec:
  type: ClusterIP
    selector:
        app: nginx-web
    ports:
        - port: 80
          targetPort: http
          protocol: TCP
          name: http
